#!/bin/bash
# 
# drawercli v1.0.6
# App drawer on Android but it's CLI,
# Copyright (c) 2023 Luis Adha


version="1.1.0"

self="termux"
depend="termuxlauncher"

num=1

source $HOME/storage/shared/termuxlauncher/.apps-launcher &>/dev/null ||  source "${EXTERNAL_STORAGE}/termuxlauncher/.apps-launcher" || source /sdcard/termuxlauncher/.apps-launcher

# initialize termuxlauncher, this will read all user-installed apps on the device
# initialize alias if any
source ~/.drawercli_aliases 2>/dev/null

function resetClipboard() {
 termux-clipboard-set ""
}

function hideSoftKeyboard() {
 input keyevent 4
}

opt="$1"
if [ -z "$opt" ]; then

hideSoftKeyboard;
# diantara xargs ada lolcat sebelumnya

launch -l | grep -Exo '[a-z0-9:_-]+' | sort --reverse --numeric-sort | xargs | xargs -n $num | fzf |termux-clipboard-set

  termux-clipboard-get >> $HOME/.drawercli_history

  launch $(termux-clipboard-get)

resetClipboard;

exit 0;

elif [ "$opt" == "-s" ] || [ "$opt" == "--skip" ]; then # THIS OPTION SKIP

launch $(launch -l | grep -o "${self}" ) &>/dev/null;

exit 0;
elif [ "$opt" == "-v" ] || [ "$opt" == "--version" ]; then

echo -e "drawercli v${version} ";
exit 0;

elif [ "$opt" == "-S" ]; then # THIS OPTION SUGGESTIONS

hideSoftKeyboard;

ERROR=${2?drawercli: option requires an argument after -- S }

      launch $(launch -l | grep -Exo [a-z0-9:_-]+ | 
sort --reverse --numeric-sort | xargs | xargs -n $num | shuf | head -n "$2" | fzf 


    echo $(basename $ERROR)

 exit 0;

elif [ "$opt" == "-u" ]; then # THIS OPTION MOST USAGE

if [ ! -f $HOME/.drawercli_history ]; then
    echo "drawercli: No history most opened apps."
    exit 1;
elif [ $(cat $HOME/.drawercli_history | wc -w) -eq 0 ]; then
    echo "drawercli: No history most opened apps. 2";
    exit 2;
else

  cat $HOME/.drawercli_history | uniq -c | sort -r | sed 's/[\t0-9]//g' | head -n 1 | fzf | termux-clipboard-set

  launch $(termux-clipboard-get)

resetClipboard;

exit 0;
fi

elif [ "$opt" == "-r" ]; then # THIS OPTION FOR REFRESH LIST APPS BY termuxlauncher

launch $(launch -l | grep "${depend}" ) &>/dev/null;

echo "drawercli: Scanning for new apps..."; sleep 1;
echo -e "Please, type \`drawercli' again to see effect!"

exit 0;
elif [ "$opt" == "-w" ] || [ "$opt" == "--see-wallpaper" ]; then
  launch $(launch -l | grep "current-wallpaper" )

exit 0;
elif [ "$opt" == "-c" ] || [ "$opt" == "--clear-history" ]; then
set +o noclobber

echo '' > ${HOME}/.drawercli_history
echo "drawercli: History was cleared!"
exit 0;

elif [ "$opt" == "-h" ] || [ "$opt" == "--help" ]; then

  echo "drawercli | -S 4 | -u "
  echo
  echo " Command-line-based app drawer to display a list of all user-installed apps on the device and many other features."
 echo
  echo "drawercli requires the termuxlauncher to be installed and used at least once to use this tool."
  echo
  echo "Available options:"
  echo
  echo -e "-S NUMBER" "\t\t" "To display app recommendations to open, recommendations will be displayed according to the given number."
  echo -e "-c, --clear-history" "\t" "To clear the history of opened app activities."
  echo -e "-r" "\t\t\t" "To refresh the list of apps, newly installed apps will be displayed after the refresh."
  echo -e "-s, --skip" "\t\t" "Does nothing, literally opens Termux itself."
  echo -e "-u" "\t\t\t" "To display the most frequently used apps."
  echo -e "-w, --see-wallpaper" "\t" "To view the wallpaper or open the current-wallpaper app."
  echo -e "-h, --help" "\t\t" "To display this help message."
  echo
  exit 1;
 else
       echo "$(basename $0): options not recognized -$opt";
   exit 1;

fi
